// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class DropingDot
{
        public const string achievement_80_points = "CgkIvYfywZoVEAIQCg"; // <GPGSID>
        public const string achievement_900_games = "CgkIvYfywZoVEAIQGA"; // <GPGSID>
        public const string achievement_10_points = "CgkIvYfywZoVEAIQAw"; // <GPGSID>
        public const string achievement_2000_games = "CgkIvYfywZoVEAIQGw"; // <GPGSID>
        public const string achievement_70_points = "CgkIvYfywZoVEAIQCQ"; // <GPGSID>
        public const string achievement_9000_games = "CgkIvYfywZoVEAIQIg"; // <GPGSID>
        public const string achievement_60_points = "CgkIvYfywZoVEAIQCA"; // <GPGSID>
        public const string achievement_50_points = "CgkIvYfywZoVEAIQBw"; // <GPGSID>
        public const string achievement_400_games = "CgkIvYfywZoVEAIQEw"; // <GPGSID>
        public const string achievement_1000_games = "CgkIvYfywZoVEAIQGQ"; // <GPGSID>
        public const string achievement_6000_games = "CgkIvYfywZoVEAIQHw"; // <GPGSID>
        public const string achievement_800_games = "CgkIvYfywZoVEAIQFw"; // <GPGSID>
        public const string achievement_30_games = "CgkIvYfywZoVEAIQDg"; // <GPGSID>
        public const string achievement_100_games = "CgkIvYfywZoVEAIQEA"; // <GPGSID>
        public const string achievement_300_games = "CgkIvYfywZoVEAIQEg"; // <GPGSID>
        public const string achievement_200_games = "CgkIvYfywZoVEAIQEQ"; // <GPGSID>
        public const string achievement_1500_games = "CgkIvYfywZoVEAIQGg"; // <GPGSID>
        public const string achievement_40_points = "CgkIvYfywZoVEAIQBg"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIvYfywZoVEAIQAQ"; // <GPGSID>
        public const string achievement_4000_games = "CgkIvYfywZoVEAIQHQ"; // <GPGSID>
        public const string achievement_700_games = "CgkIvYfywZoVEAIQFg"; // <GPGSID>
        public const string achievement_500_games = "CgkIvYfywZoVEAIQFA"; // <GPGSID>
        public const string achievement_welcome_ = "CgkIvYfywZoVEAIQAg"; // <GPGSID>
        public const string achievement_30_points = "CgkIvYfywZoVEAIQBQ"; // <GPGSID>
        public const string achievement_100_points = "CgkIvYfywZoVEAIQDA"; // <GPGSID>
        public const string achievement_10000_games = "CgkIvYfywZoVEAIQIw"; // <GPGSID>
        public const string achievement_150_points = "CgkIvYfywZoVEAIQDQ"; // <GPGSID>
        public const string achievement_600_games = "CgkIvYfywZoVEAIQFQ"; // <GPGSID>
        public const string achievement_5000_games = "CgkIvYfywZoVEAIQHg"; // <GPGSID>
        public const string achievement_90_points = "CgkIvYfywZoVEAIQCw"; // <GPGSID>
        public const string achievement_3000_games = "CgkIvYfywZoVEAIQHA"; // <GPGSID>
        public const string achievement_20_points = "CgkIvYfywZoVEAIQBA"; // <GPGSID>
        public const string achievement_8000_games = "CgkIvYfywZoVEAIQIQ"; // <GPGSID>
        public const string achievement_50_games = "CgkIvYfywZoVEAIQDw"; // <GPGSID>
        public const string achievement_7000_games = "CgkIvYfywZoVEAIQIA"; // <GPGSID>

}

